name: Notebook Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'Notebook/**'
  workflow_dispatch:

jobs:
  generate-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Update and install prerequisites
        run: sudo apt-get update
        
      - name: Update and install prerequisites
        run: sudo apt-get install -y aptitude
        
      - name: Install aptitude
        run: sudo apt-get install -y aptitude

      - name: Install TeX Live and extra packages
        run: sudo aptitude install texlive texlive-latex-extra
      
      - name: Generate PDF Notebook
        run: notebook-generator ./Notebook --author "Mauricio Cari Leal" --size 9 --image ./.Assets/UC-Logo
